In [1]:
# Multiple Regression
#py = b0+b1*x1+b2*x2+===bn*xn 

# Nominal : Male/Female, Red/Green, delhi/kolkata/mumbai

# Ordinal : Poor/Satisfac/Good/Verry Good, o/e/a/b/c/d/f

In [15]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [5]:
df.area

0    2600
1    3000
2    3200
3    3600
4    4000
5    4100
Name: area, dtype: int64

In [9]:
df[["bedrooms", "price", "age", "area"]]

bedrooms   price  age  area
0       3.0  550000   20  2600
1       4.0  565000   15  3000
2       NaN  610000   18  3200
3       3.0  595000   30  3600
4       5.0  760000    8  4000
5       6.0  810000    8  4100

In [10]:
df.bedrooms.median()

4.0

In [11]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df.drop("price", axis="columns"), df.price)

LinearRegression()

In [18]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
reg.intercept_

221323.00186540443

In [23]:
reg.predict([[3000,4,30]])

array([554114.31074458])

In [25]:
reg.predict([[4100,6,8]])

array([795258.55102673])

In [26]:
reg.score(df.drop("price", axis="columns"), df.price)

0.9550196399325819